stages:
  - build
  - test

variables:
  CMAKE_BUILD_TYPE: "Release"

before_script:
  - apt-get update --yes
  - apt-get install --yes flex gcc cmake

build_project:
  stage: build
  script:
    - make
    - make test