stages:
  - build
  - test

variables:
  CMAKE_BUILD_TYPE: "Release"

before_script:
  - apt-get update --yes
  - apt-get install --yes flex gcc valgrind

build_project:
  stage: build
  script:
    - make
    - make test
    - make valgrind
  artifacts:
    paths:
      - build/*valgrind.log.txt